sudo: false

language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle "$SYMFONY_VERSION"; fi

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
